#!/usr/bin/env python3
"""
sync_agent.py -- keep the distress-fraud-analyst AGENT MD in sync with its brain docs.

The agent reads its brain (playbook/spec/calibration log/ledger) LIVE on every run, so content
is always current. This job keeps the wrapper md's POINTERS + a freshness stamp accurate: it
hashes the brain docs, and when any change, it regenerates an AUTO-SYNCED manifest block in the
agent md and appends a line to AGENT_SYNC_LOG.md. Cheap + deterministic + idempotent (no change
when nothing changed) -- safe to run every 10 minutes from cron.

  python3 sync_agent.py            # sync if anything changed (default)
  python3 sync_agent.py --check    # print CHANGED / NO_CHANGE only (no writes) -- for the cron gate
"""
import os, sys, json, hashlib, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
AGENT_MD = os.path.expanduser("~/.claude/agents/distress-fraud-analyst.md")
STATE = os.path.join(HERE, "AGENT_SYNC_STATE.json")
LOG = os.path.join(HERE, "AGENT_SYNC_LOG.md")
MARK_A, MARK_B = "<!-- AUTO-SYNCED:BRAIN -->", "<!-- /AUTO-SYNCED:BRAIN -->"

# the brain: docs whose changes the agent should be aware of (label -> filename in HERE)
BRAIN = [
    ("Operating playbook", "AGENT_PLAYBOOK.md"),
    ("Distress/fraud spec", "DISTRESS_AGENT.md"),
    ("Calibration log (lessons)", "CALIBRATION_LOG.md"),
    ("Calibration ledger (per-ticker)", "CALIBRATION_LEDGER.csv"),
    ("Valuation algorithm", "ALGORITHM.md"),
    ("Valuation calibration log", "MS_CALIBRATION_LOG.md"),
    ("Screen engine", "distress_screen.py"),
]


def _manifest():
    m = {}
    for label, fn in BRAIN:
        p = os.path.join(HERE, fn)
        if not os.path.exists(p):
            m[fn] = {"label": label, "exists": False}
            continue
        b = open(p, "rb").read()
        m[fn] = {"label": label, "exists": True,
                 "sha": hashlib.sha1(b).hexdigest()[:12],
                 "lines": b.count(b"\n") + 1,
                 "mtime": datetime.datetime.fromtimestamp(os.path.getmtime(p)).strftime("%Y-%m-%d %H:%M")}
    return m


def _changed(prev, cur):
    diffs = []
    for fn, c in cur.items():
        p = (prev or {}).get(fn, {})
        if p.get("sha") != c.get("sha") or p.get("exists") != c.get("exists"):
            diffs.append(fn)
    for fn in (prev or {}):
        if fn not in cur:
            diffs.append(fn)
    return sorted(set(diffs))


def _block(cur, stamp):
    rows = [f"| {c['label']} | `{fn}` | {c.get('lines','-')} | {c.get('mtime','MISSING')} | `{c.get('sha','--')}` |"
            for fn, c in cur.items()]
    return (f"{MARK_A}\n"
            f"### Brain manifest (auto-synced {stamp})\n"
            f"_Read these live on every run — they are the source of truth. This block is regenerated by "
            f"`sync_agent.py` whenever a brain doc changes._\n\n"
            f"| Doc | File | Lines | Last modified | Hash |\n|---|---|---:|---|---|\n"
            + "\n".join(rows) + f"\n{MARK_B}")


def _splice(text, block):
    if MARK_A in text and MARK_B in text:
        a = text.index(MARK_A); b = text.index(MARK_B) + len(MARK_B)
        return text[:a] + block + text[b:]
    return text.rstrip() + "\n\n---\n" + block + "\n"


def main():
    check_only = "--check" in sys.argv
    cur = _manifest()
    prev = json.load(open(STATE)) if os.path.exists(STATE) else {}
    diffs = _changed(prev.get("manifest", {}), cur)
    has_block = os.path.exists(AGENT_MD) and MARK_A in open(AGENT_MD).read()
    needs = bool(diffs) or not has_block

    if check_only:
        print("CHANGED" if needs else "NO_CHANGE")
        if diffs:
            print("changed:", ", ".join(diffs))
        return 0 if not needs else 1

    if not needs:
        print("NO_CHANGE — agent md already in sync")
        return 0

    stamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    if os.path.exists(AGENT_MD):
        text = open(AGENT_MD).read()
        open(AGENT_MD, "w").write(_splice(text, _block(cur, stamp)))
    json.dump({"manifest": cur, "synced": stamp}, open(STATE, "w"), indent=2)
    # append log
    newlog = not os.path.exists(LOG)
    with open(LOG, "a") as f:
        if newlog:
            f.write("# Agent sync log\n\n_When a brain doc changes, the distress-fraud-analyst agent "
                    "md manifest is regenerated. Each line = one sync._\n\n")
        what = ", ".join(diffs) if diffs else "(initialised manifest block)"
        f.write(f"- {stamp} — synced; changed: {what}\n")
    print(f"SYNCED {stamp} — changed: {', '.join(diffs) if diffs else '(init)'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
